### PR TITLE
overhaul broken swissid authentication 

### PR DESCRIPTION
**Pull request by abertschi**
Pull request for issue #20. The swissid authentication changed for postcards. This PR keeps track of current state of bug fix.

- [x] obtain a saml response and relay value using username and password
- [x] obtain an access token with saml response
- [x] figure out if legacy method (without swissid) can be fixed or was removed
- [x] find out new endpoints which are compatible with swissid access_token #22

### CODE REVIEW

**Comment by abertschi** [comment]
The current state of this pull request can successfully fetch an access_token using swissid.

With such access_token the existing endpoints are now longer compatible. An access_token obtained with swissid will throw an status_code: 401 when being used with the endpoints https://postcardcreator.post.ch/rest/2.2/.

In order for this to work, the endpoints at `https://pccweb.api.post.ch/secure/api/mobile/v1` must be reverse engineered.

postcard_creator_wrapper, which currently uses https://postcardcreator.post.ch/rest/2.2/ can still be used with the legacy method (username and password without swissid). However, Swiss Post pushed most accounts to leave legacy method and only support swissid.

**Comment by wp99cp** [comment]
Thanks for reporting the current state of this issue. I'm working on a solution and will make a pull request when finished.
I'm now able to receive the quota over the new API. 

    def get_quota(self):
        logger.debug('fetching quota')
        endpoint = '/user/quota'
        return self._do_op('get', endpoint).json()

Details will follow...

**Comment by wp99cp** [comment]
**Setup for Reverse-engineering the new API**

To reverse-engineering the new API, you can use an android emulator (like Android Studio). Then install the PostCardCreator App through the App Store.

To monitor the traffic, we can use Burp Suite Community Edition to create a proxy server, over which the traffic from our emulator runs. See https://www.yodiw.com/monitor-android-network-traffic-with-burp/ for further explanation. Additionally: In the Proxy Options, you need to set a TLS Pass-Through for account.post.ch to sign in to the app successfully. Also, make sure to Intercept all requests (with the default options, not all API-calls are visible).

**Comment by abertschi** [comment]
> Thanks for reporting the current state of this issue. I'm working on a solution...

hey there, thanks for reaching out! feel free to submit some code which does some parts of the remaining work. :+1:

**Pull request merged**
